/// Flutter icons Especial_Icons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Especial_Icons
///      fonts:
///       - asset: fonts/Especial_Icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Especial_Icons {
  Especial_Icons._();

  static const _kFontFam = 'Especial_Icons';
  static const String _kFontPkg = null;

  static const IconData scan = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
